#!/bin/sh

set -e

exec 3>&1
exec 1>&2

#
# Get parameters from the pipeline
#
payload=$(cat <&0)


BOT_TOKEN=$(echo $payload | jq -r '(.source.bot_token // "")')
text="$(echo $payload | jq '(.params.text // "text is empty")')"
CHAT_ID="$(echo $payload | jq -r '(.params.chat_id // "")')"
PROXY="$(echo $payload | jq -r '(.source.proxy // "")')"

#
# Check mandatory parameters
#
if [ -z "$BOT_TOKEN" ]; then
     printf "\nError! The Telegram bot token is not specified! Please, add the 'source.bot_token' property to your resource declaration.\n"
     exit 1
fi

if [ -z "$CHAT_ID" ]; then
     printf "\nError! The Telegram chat ID is not specified! Please, add the 'params.chat_id' property to your resource parameters.}\n"
     exit 1
fi

if [ -n "$PROXY" ]; then
    https_proxy=$PROXY
fi

#
# Send message
#
text="$(eval printf ${text} )"
URL="https://api.telegram.org/bot${BOT_TOKEN}/sendMessage"
curl -X POST --data chat_id=${CHAT_ID//\"/} --data text="${text}" --data parse_mode=Markdown "$URL"

#
# Return version
#
timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
echo "$timestamp" | jq -s add >&3
